<!DOCTYPE html>
<html lang="en" id="id1">

<head>
    <title>Budget Report</title>
    <link rel="stylesheet" href="/public/assets/newstyles.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/c119b7fc61.js" crossorigin="anonymous"></script>
</head>

<style>
a {
    color: #16c79a;
}

h1,
h2,
h3 {
    text-align: center;
}

table {
    width: 100%;
    background: #e2dfdf;
    text-align: center;
    margin: 20px;


}

table,
th,
td {

    border-collapse: collapse;
    border: solid #c7b4b4 2px;
}

th,
td {
    border-bottom: 1px solid #fff;
    padding: 8px;
}

.container {
    width: 80%;
    max-width: none;
}

.date-time-container {
    display: flex;
    font-size: 12px;
}
</style>

<?php 
if(!isset($moderator)) $moderator= false;
if(!isset($treasurer)) $treasurer= false;
$organization = $admin =$registered_user = $guest_user = false;

if(isset($_SESSION ["user"] ["user_type"])){
    if($_SESSION ["user"] ["user_type"] == "organization"){
        $organization = true;
    }
    
    if($_SESSION ["user"] ["user_type"] == "admin"){
        $admin = true;
    }

    if($_SESSION ["user"] ["user_type"] == "registered_user"){
        $registered_user = true;
    }
    
}else{
    $guest_user= true;
}
?>

<body>
    <header class="header">
        <div style="width: 20%;"><a class=" logo ">
                <img src="/Public/assets/visal logo.png ">
            </a>
        </div>

        <div style="width: 60%; text-align:center">
            <p style="color: #16C79A;">Report generated by <a href="/user/home"><b>Community
                        Retreat</b> </a></p>
        </div>

        <div class="date-time-container" style="width: 20%;">
            <p>Date and Time: <span id='date-time'></span>.</p>
            <br><br>
        </div>
    </header>
    <h1><?= $event_name ?></h1>
    <h3>Budget Report</h3>
    <div class="container">
        <div class="container">
            <table>
                <tr>
                    <th>Date</th>
                    <th>Description</th>
                    <th>Income</th>
                    <th>Expense</th>
                </tr>
                <?php foreach($report as $report) { ?>
                <tr>
                    <td><?= $report["date"] ?></td>
                    <td><?= $report["details"] ?></td>
                    <td><?php if(substr($report["record_id"],0,3)==="INC"){ echo $report["amount"];} ?>
                    </td>
                    <td><?php if(substr($report["record_id"],0,3)==="EXP"){ echo $report["amount"];} ?></td>
                </tr>
                <?php } ?>
                <tr>
                    <td><b>Total</b></td>
                    <td></td>
                    <td><b><?= $income_sum ?></b></td>
                    <td><b><?= $expense_sum ?></b></td>
                </tr>
            </table>
        </div>
        <div class="container">
            <h2>Income</h2>
            <table>
                <tr>
                    <th>Date</th>
                    <th>Description</th>
                    <th>Income</th>
                    <th>Edited by</th>
                </tr>
                <?php foreach($income_report as $income_report) { ?>

                <tr
                    style="background-color: <?php if($income_report["status"]=="current") echo '#29BB89'; elseif ($income_report["status"]=="deleted") echo '#FF2442'; elseif ($income_report["status"]=="updated") echo '#FFE268'; ?>">
                    <td><?= $income_report["date"] ?></td>
                    <td><?= $income_report["details"] ?></td>
                    <td><?= $income_report["amount"] ?></td>
                    <td><?= $income_report["username"] ?></td>
                </tr>
                <?php if($income_report["status"]=="deleted") echo '<tr style="background-color: white; height:30px;"></tr>'; ?>
                <?php } ?>
            </table>
        </div>
        <div class=" container">
            <h2>Expense</h2>
            <table>
                <tr>
                    <th>Date</th>
                    <th>Description</th>
                    <th>Expense</th>
                    <th>Edited by</th>
                </tr>
                <?php foreach($expense_report as $expense_report) { ?>
                <tr
                    style="background-color: <?php if($expense_report["status"]=="current") echo '#29BB89'; elseif ($expense_report["status"]=="deleted") echo '#FF2442'; elseif ($expense_report["status"]=="updated") echo '#FFE268'; ?>">
                    <td><?= $expense_report["date"] ?></td>
                    <td><?= $expense_report["details"] ?></td>
                    <td><?= $expense_report["amount"] ?></td>
                    <td><?= $expense_report["username"] ?></td>
                </tr>
                <?php if($expense_report["status"]=="deleted") echo '<tr style="background-color: white; height:30px;"></tr>'; ?>
                <?php } ?>
            </table>
        </div>
    </div>

</body>

<script>
var dt = new Date();
document.getElementById('date-time').innerHTML = dt;
</script>