<!DOCTYPE html>
<html lang="en" id="id1">

<head>
    <title>Budget Report</title>
    <link rel="stylesheet" href="/public/assets/newstyles.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/c119b7fc61.js" crossorigin="anonymous"></script>
</head>

<style>
a {
    color: #16c79a;
}

h1,
h2,
h3 {
    text-align: center;
}

table {
    width: 100%;
    background: #ececec;
    text-align: center;
    margin: 20px;


}

table,
th,
td {

    border-collapse: collapse;
}

th,
td {
    border-bottom: 1px solid #fff;
    padding: 8px;
}

.container {
    width: 80%;
    max-width: none;
}

.date-time-container {
    display: flex;
    font-size: 12px;
}

.color-container {

    border-radius: 8px;
    width: 15%;
    margin: 20px;
    padding: 10px;
}

.right {
    text-align: right;
}

/*.scroll {
    overflow: scroll;
}*/


@media screen and (max-width:800px) {
    .table {
        width: 100%;
        text-align: center;
    }

    .container {
        width: 100%;
    }
}
</style>

<?php 
if(!isset($moderator)) $moderator= false;
if(!isset($treasurer)) $treasurer= false;
$organization = $admin =$registered_user = $guest_user = false;

if(isset($_SESSION ["user"] ["user_type"])){
    if($_SESSION ["user"] ["user_type"] == "organization"){
        $organization = true;
    }
    
    if($_SESSION ["user"] ["user_type"] == "admin"){
        $admin = true;
    }

    if($_SESSION ["user"] ["user_type"] == "registered_user"){
        $registered_user = true;
    }
    
}else{
    $guest_user= true;
}
?>

<body>
    <header class="header">
        <div style="width: 20%;"><a class=" logo ">
                <img src="/Public/assets/visal logo.png ">
            </a>
        </div>

        <div style="width: 60%; text-align:center">
            <p style="color: #16C79A;">Report generated by <a href="/User/home"><b>Community
                        Retreat</b> </a></p>
        </div>

        <div class="date-time-container" style="width: 20%;">
            <p>Date and Time: <span id='date-time'></span>.</p>
            <br><br>
        </div>
    </header>
    <h1><?= $event_name ?></h1>
    <h3>Budget Report</h3>
    <div class="container">
        <div class="container">
            <table>
                <tr>
                    <th>Date</th>
                    <th>Description</th>
                    <th class="right">Income</th>
                    <th class="right">Expense</th>
                </tr>
                <?php foreach($report as $report) { ?>
                <tr>
                    <td><?= $report["date"] ?></td>
                    <td class="scroll"><?= $report["details"] ?></td>
                    <td class="right"><?php if(substr($report["record_id"],0,3)==="INC"){ echo $report["amount"];} ?>
                    </td>
                    <td class="right"><?php if(substr($report["record_id"],0,3)==="EXP"){ echo $report["amount"];} ?>
                    </td>
                </tr>
                <?php } ?>
                <tr>
                    <td><b>Total</b></td>
                    <td></td>
                    <td class="right"><b><?= $income_sum ?></b></td>
                    <td class="right"><b><?= $expense_sum ?></b></td>
                </tr>
            </table>
        </div>
        <div class="container">
            <div style="display: flex; text-align:center; justify-content: center;">
                <div class="color-container" style="background-color: #01937C;"><b>Current</b></div>
                <div class="color-container" style="background-color: #FF0000;"><b>Deleted</b></div>
                <div class="color-container" style="background-color: #FAFF00;"><b>Updated</b></div>
            </div>


        </div>
        <div class=" container">
            <h2>Income</h2>
            <table>
                <tr>
                    <th>Date</th>
                    <th>Description</th>
                    <th class="right">Income</th>
                    <th class="right">Edited by</th>
                </tr>
                <?php foreach($income_report as $income_report) { ?>

                <tr
                    style="background-color: <?php if($income_report["status"]=="current") echo '#01937C'; elseif ($income_report["status"]=="deleted") echo '#FF0000'; elseif ($income_report["status"]=="updated") echo '#FAFF00'; ?>">
                    <td><?= $income_report["date"] ?></td>
                    <td class="scroll"><?= $income_report["details"] ?></td>
                    <td class="right"><?= $income_report["amount"] ?></td>
                    <td class="right"><?= $income_report["username"] ?></td>
                </tr>
                <?php if($income_report["status"]=="deleted") echo '<tr style="background-color: white; height:30px;"></tr>'; ?>
                <?php } ?>
            </table>
        </div>
        <div class=" container">
            <h2>Expense</h2>
            <table>
                <tr>
                    <th>Date</th>
                    <th>Description</th>
                    <th class="right">Expense</th>
                    <th class="right">Edited by</th>
                </tr>
                <?php foreach($expense_report as $expense_report) { ?>
                <tr
                    style="background-color: <?php if($expense_report["status"]=="current") echo '#01937C'; elseif ($expense_report["status"]=="deleted") echo '#FF0000'; elseif ($expense_report["status"]=="updated") echo '#FAFF00'; ?>">
                    <td><?= $expense_report["date"] ?></td>
                    <td class="scroll"><?= $expense_report["details"] ?></td>
                    <td class="right"><?= $expense_report["amount"] ?></td>
                    <td class="right"><?= $expense_report["username"] ?></td>
                </tr>
                <?php if($expense_report["status"]=="deleted") echo '<tr style="background-color: white; height:30px;"></tr>'; ?>
                <?php } ?>
            </table>
        </div>
    </div>

</body>

<script>
var dt = new Date();
document.getElementById('date-time').innerHTML = dt;
</script>