<!DOCTYPE html>
<html lang="en" id="id1">

<head>
    <title>Donation Report</title>
    <link rel="stylesheet" href="/Public/assets/newstyles.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/c119b7fc61.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
</head>

<style>
    .canvas {
        display: -webkit-inline-box;
        width: 100%;
    }

    .community-retreat {
        color: #16c79a;
    }

    h1,
    h3 {
        text-align: center;
    }

    .table {
        width: 100%;
        background: #e2dfdf;
        text-align: center;
        margin: 20px;
        border-collapse: collapse;
    }

    th,
    td {
        border-bottom: 1px solid #fff;
        padding: 8px;
        border-collapse: collapse;
    }

    .container {
        width: 80%;
        max-width: none;
    }

    .date-time-container {
        display: flex;
        font-size: 12px;
    }

    .logo-container {
        width: 20%;
    }

    .amount {
        text-align: right;
    }
</style>

<?php
if (!isset($moderator)) $moderator = false;
if (!isset($treasurer)) $treasurer = false;
$organization = $admin = $registered_user = $guest_user = false;

if (isset($_SESSION["user"]["user_type"])) {
    if ($_SESSION["user"]["user_type"] == "organization") {
        $organization = true;
    }

    if ($_SESSION["user"]["user_type"] == "admin") {
        $admin = true;
    }

    if ($_SESSION["user"]["user_type"] == "registered_user") {
        $registered_user = true;
    }
} else {
    $guest_user = true;
}
?>


<body>
    <header class="header">
        <div class="logo-container"><a class=" logo ">
                <img src="/Public/assets/visal logo.png ">
            </a>
        </div>

        <div style="width: 60%; text-align:center">
            <p style="color: #16C79A;">Report generated by <a class="community-retreat" href=" /User/home"><b>CommunityRetreat</b> </a>
            </p>
        </div>

        <div class="date-time-container" style="width: 20%;">
            <p>Date and Time: <span id='date-time'></span>.</p>
            <br><br>
        </div>
    </header>
    <div class="container">
        <div class="container">
            <h1><?= $event_name ?></h1>
            <h3>Donation Report</h3>
            <div class="center" style="text-align: center;">
                <canvas class="canvas" id="myChart"></canvas>
            </div>

            <div>
                <form action="/Donations/donationReport?event_id=<?= $_GET["event_id"] ?>" method="post">
                    <label for="donate_date">Sort by donating date</label>
                    <select class="form-ctrl" id="donate_date" name="date" onchange="this.form.submit()">
                    <option value="all" selected>all</option>
                    <?php foreach($period as $period) { ?>
                    <option value="<?= $period ?>" <?php if($selected_date ==$period) echo "selected"; ?>><?= $period ?></option>
                <?php } ?>   
                </select>
                </form>
            </div>
            <table class="table">
                <!--Display the report of all the donations-->
                <tr>
                    <th>Date</th>
                    <th>Donor</th>
                    <th class="amount">Amount</th>
                </tr>
                <?php foreach ($donations as $donation) { ?>
                    <tr>
                        <td><?= $donation["date"] ?></td>
                        <td><?= $donation["username"] ?></td>
                        <td class="amount"><?php echo 'Rs. ' . number_format($donation["amount"], 2) ?></td>
                    </tr>
                <?php } ?>
                <tr>
                    <td><b>Total</b></td>
                    <td></td>
                    <td class="amount"><b><?php echo 'Rs. ' . number_format($donation_sum, 2) ?></b></td>
                </tr>
            </table>
        </div>

    </div>

</body>

<script>
    /*send data to the graph*/
    const data = <?= $donations_graph ?>;
    console.log(data);
    const backgroundColor = ['#6F69AC', '#FEC260', '#93B5C6', '#FA8072']
    const borderColor = ['#6F69AC80', '#FEC26080', '#93B5C680', '#FA807280']

    let keys = [];
    let amounts = [];
    for (const event in data) {
        keys.push(data[event]["day"]);
        amounts.push(data[event]["donation_sum"]);
    }

    //console.log(keys, amount);

    var myLineChart = new Chart('myChart', {
        type: 'line',
        data: {
            labels: keys,
            datasets: [{
                label: 'Donations',
                data: amounts,
                backgroundColor: backgroundColor[0],
                borderColor: borderColor[0],
                fill: false
            }]

        },
        options: {
            responsive: true,
            scales: {
                yAxes: [{
                    scaleLabel: {
                        display: true,
                        labelString: 'Amount',
                    },
                }],
                xAxes: [{
                    scaleLabel: {
                        display: true,
                        labelString: 'Date',
                    },
                    ticks: {
                        beginAtZero: true,
                        userCallback: function(label, index, labels) {
                            // when the floored value is the same as the value we have a whole number
                            if (Math.floor(label) === label) {
                                return label;
                            }

                        },
                    }

                }]
            }
        }
    });
</script>

<script>
    /*get date and time*/
    var dt = new Date();
    document.getElementById('date-time').innerHTML = dt;
</script>